### ISSUE TITLE
Docs: there's no `sync` API in `async.lua` file

### ISSUE THREAD

**Issue by linrongbin16** [lewis6991/async.nvim#5]
Hi,

In README docs: https://github.com/lewis6991/async.nvim/blob/bad4edbb2917324cd11662dc0209ce53f6c8bc23/README.md?plain=1#L63

It mentions there's a `sync` API, but it actually doesn't exists in the `async.lua` file.

Is it renamed to `run`? or `join` or `wait`?

**Comment by lewis6991** [comment]
PR welcome.

**Comment by linrongbin16** [comment]
> PR welcome.

sure, while could you help confirm which api it is?

**Comment by lewis6991** [comment]
Whatever is in the code.
